- server/db/db.go
- server/db/user.go
- server/db/verification.go
- server/graph/generated/generated.go
- server/graph/model/models_gen.go
- server/graph/schema.graphqls
- server/graph/schema.resolvers.go
- server/server.go
- server/utils/verificationToken.go
> feat: add resolver for token verification

- server/graph/generated/generated.go
- server/graph/model/models_gen.go
- server/graph/schema.graphqls
- server/graph/schema.resolvers.go
- server/resolvers/forgotPassword.go
- server/resolvers/login.go
- server/resolvers/resetPassword.go
- server/resolvers/signup.go
- server/resolvers/token.go
- server/resolvers/verifyEmail.go
> feat:allow signup without verification

- server/db/db.go
- server/db/user.go
- server/graph/generated/generated.go
- server/graph/model/models_gen.go
- server/graph/schema.graphqls
- server/graph/schema.resolvers.go
- server/resolvers/adminUpdateUser.go
> feat: allow admin to user profile

- README.md
- server/constants/constants.go
- server/env.go
- server/graph/generated/generated.go
- server/graph/model/models_gen.go
- server/graph/schema.graphqls
- server/graph/schema.resolvers.go
- server/handlers/oauthCallback.go
- server/handlers/verifyEmail.go
- server/resolvers/magicLogin.go
- server/utils/email.go
- server/utils/meta.go
> feat: add support for magic link login

- server/handlers/oauthCallback.go
- server/utils/cookie.go
Set & Delete cookie for client side app
Resolves: #71
> feat: set & delete client cookie

- server/constants/constants.go
- server/handlers/verifyEmail.go
- server/main.go
- server/resolvers/verifyEmail.go
- server/utils/cookie.go
- server/utils/urls.go
- server/utils/verificationToken.go
Fix: verification email redirection
Resolves #70
> fix: redirect link for verification handler

- server/db/arangodb.go
- server/db/db.go
- server/db/mongodb.go
- server/db/session.go
- server/db/user.go
- server/db/verificationRequests.go
- server/enum/dbType.go
- server/go.mod
- server/go.sum
- server/resolvers/signup.go
> feat: add mongodb support

- .github/workflows/release.yaml
- .gitignore
- Dockerfile
- Makefile
- app/README.md
- dashboard/README.md
- dashboard/esbuild.config.js
- dashboard/package-lock.json
- dashboard/package.json
- dashboard/src/App.tsx
- dashboard/src/index.tsx
- dashboard/tsconfig.json
- scripts/build-mac.sh
- server/handlers/dashboard.go
- server/main.go
- templates/dashboard.tmpl
Completes the boilerplate setup as per #90
> feat: add dashboard setup with esbuild + chakra-ui

- server/email/email.go
> fix: send mail from param

- server/constants/pagination.go
- server/db/models/verification_requests.go
- server/db/providers/arangodb/user.go
- server/db/providers/arangodb/verification_requests.go
- server/db/providers/mongodb/user.go
- server/db/providers/mongodb/verification_requests.go
- server/db/providers/providers.go
- server/db/providers/sql/user.go
- server/db/providers/sql/verification_requests.go
- server/graph/generated/generated.go
- server/graph/model/models_gen.go
- server/graph/schema.graphqls
- server/graph/schema.resolvers.go
- server/resolvers/users.go
- server/resolvers/verification_requests.go
- server/test/resolvers_test.go
- server/test/users_test.go
- server/test/verification_requests_test.go
- server/utils/pagination.go
- Add pagination for `_users` query
- Add pagination for `_verification_requests` query
> feat: add pagination for users & verification_requests

- dashboard/src/components/InputField.tsx
- dashboard/src/constants.ts
- dashboard/src/graphql/queries/index.ts
- dashboard/src/pages/Environment.tsx
- add support for more JWT encryption types in dashboard
- https://github.com/authorizerdev/authorizer/issues/122
- N/A
> support for more jwt encryption types added

- .gitignore
- server/sessionstore/redis_store.go
- server/sessionstore/session.go
- server/sessionstore/session_client.go
Adds the redis cluster client as a session store.
> Add redis cluster client as a session store.

- app/package-lock.json
- app/package.json
- app/src/Root.tsx
- app/src/pages/login.tsx
- app/src/pages/signup.tsx
- app/src/theme.ts
- app/src/utils/common.ts
- decouple signup and login routes in app
- https://github.com/authorizerdev/authorizer/issues/167
> update: separate routes for login and signup added

- server/db/models/model.go
> fix: collections names

- server/db/providers/arangodb/otp.go
- server/db/providers/mongodb/otp.go
- server/db/providers/sql/otp.go
- server/resolvers/verify_otp.go
- server/test/resolvers_test.go
- server/test/verify_otp_test.go
> update: verify otp resolver and test added

- dashboard/src/pages/Users.tsx
Adds overflow by using Chakra's `TableContainer`
#220 
https://user-images.githubusercontent.com/61158210/187490640-6695561f-470f-4bbf-b4ae-4e46efc6b153.mov
> fix(dashboard): users table overflow

- server/main.go
> feat(server): add log to show PORT

- app/src/App.tsx
> fix(type): __authorizer__ on window

- server/constants/verification_types.go
- server/resolvers/delete_user.go
> fix: remove entries from otp + verification when user is deleted

- app/.prettierrc.json
- app/package-lock.json
- app/package.json
- app/src/App.tsx
- app/src/Root.tsx
- app/src/theme.ts
- app/src/utils/common.ts
> chore(app): add prettier

- server/db/models/email_templates.go
- server/db/models/env.go
- server/db/models/user.go
- server/db/models/verification_requests.go
- server/db/models/webhook.go
- server/db/models/webhook_log.go
> fix(server): text type for sql server 2019

- server/db/providers/sql/provider.go
multiple null values for unique constrained column is not allowed on sqlserver
Resolves #278
> fix(server): sql server not allow multiple null

- server/graph/generated/generated.go
- server/graph/model/models_gen.go
- server/graph/schema.graphqls
- server/resolvers/validate_jwt_token.go
- server/test/resolvers_test.go
- server/test/validate_jwt_token_test.go
Adds JWT claims to validation request so that user can validate and use those claims in middleware of backend apis
> feat(server): add jwt claims as part of validation endpoint

- server/handlers/token.go
It breaks out of the else statement if refresh token fails to validate.
Fixes the problem were a invalid refresh token can be used to generate new good tokens
Big dislaimer though, I have no experience with GO and I just saw how the same logic was made for sessionKey, and noticed there was no return statements. I haven't tested the code, since I have no clue how to build in GO lang.
> fixed validation of refresh token

- server/db/providers/sql/user.go
Resolves: https://github.com/authorizerdev/docs/issues/18
> fix(sql): user deletion

- dashboard/src/components/DeleteEmailTemplateModal.tsx
- dashboard/src/components/DeleteUserModal.tsx
- dashboard/src/components/DeleteWebhookModal.tsx
- dashboard/src/components/EditUserModal.tsx
- dashboard/src/components/EnvComponents/JWTConfiguration.tsx
- dashboard/src/components/GenerateKeysModal.tsx
- dashboard/src/components/InviteMembersModal.tsx
- dashboard/src/components/UpdateEmailTemplateModal.tsx
- dashboard/src/components/UpdateWebhookModal.tsx
- dashboard/src/pages/Auth.tsx
- dashboard/src/pages/Environment.tsx
- dashboard/src/pages/Users.tsx
Moves toast(notification) to top-right.
Was previously bottom-right.
Found it annoying that it often blocked the save button which
is also at the bottom-right of the page.
> change toast position to top-right

- server/handlers/authorize.go
- server/handlers/oauth_callback.go
Update deprecated functions and minor fixes.
Might want to just double check that the commit: 9540c367f10fce56039849fed8012c0ccbcb1772 does not cause problems for previous go versions, as it is stated that go 1.15 =< is needed for this project.
> Rnd warning fixes

- server/graph/generated/generated.go
- server/graph/model/models_gen.go
- server/graph/schema.graphqls
- server/graph/schema.resolvers.go
- server/resolvers/user.go
- server/test/resolvers_test.go
- server/test/user_test.go
Add API to get user by id using admin secret.
> Add get user api for admin

- Makefile
- app/package-lock.json
- app/package.json
- server/constants/db_types.go
- server/constants/env.go
- server/db/db.go
- server/db/providers/couchbase/email_template.go
- server/db/providers/couchbase/env.go
- server/db/providers/couchbase/otp.go
- server/db/providers/couchbase/provider.go
- server/db/providers/couchbase/session.go
- server/db/providers/couchbase/shared.go
- server/db/providers/couchbase/user.go
- server/db/providers/couchbase/verification_requests.go
- server/db/providers/couchbase/webhook.go
- server/db/providers/couchbase/webhook_log.go
- server/env/env.go
- server/go.mod
- server/go.sum
- server/memorystore/required_env_store.go
- server/test/resolvers_test.go
> feat: add couchbase provider

- Dockerfile
- Makefile
- server/db/providers/arangodb/email_template.go
- server/db/providers/arangodb/provider.go
- server/db/providers/arangodb/user.go
- server/db/providers/arangodb/verification_requests.go
- server/db/providers/arangodb/webhook.go
- server/db/providers/arangodb/webhook_log.go
Adding support for db username, password and ca cert will enable users to connect arangodb cloud platform
> [server] add support for arangodb cert, username, password

- .github/FUNDING.yml
> feat: github sponsor

- server/handlers/jwks.go
- server/handlers/openid_config.go
- server/handlers/userinfo.go
- server/token/auth_token.go
Add missing openid configs
Resolves #304
> fix: add missing info for openid config

- dashboard/src/components/EnvComponents/Features.tsx
- dashboard/src/components/InputField.tsx
> Features enhancement (Disable/Enable)

- server/handlers/verify_email.go
- server/resolvers/magic_link_login.go
- server/resolvers/resend_verify_email.go
- server/resolvers/signup.go
- server/resolvers/update_profile.go
- server/resolvers/update_user.go
- server/utils/common.go
- server/utils/response.go
While verifying emails,
it redirects with error in case of error
Resolves #309
> [server]fix: error redirection for email verification

- server/graph/generated/generated.go
- server/graph/model/models_gen.go
- server/graph/schema.graphqls
- server/resolvers/user.go
- server/test/user_test.go
Update `_user` [admin] query to get user by either ID or by Email
Resolves #352
> [server] add ability to get user by email

- app/package-lock.json
- app/package.json
- app/src/pages/login.tsx
- app/yarn.lock
- server/authenticators/providers/providers.go
- server/authenticators/providers/totp/totp.go
- server/graph/generated/generated.go
- server/graph/model/models_gen.go
- server/graph/schema.graphqls
- server/resolvers/verify_otp.go
- server/test/totp_login_test.go
- Add UI for TOTP
- Add recovery code validation to `verify_otp` resolver
- Rename `totp` -> `is_totp` in `verify_otp`
Fixes #419
> feat: add totp UI & recovery code

- app/package-lock.json
- app/package.json
- app/src/pages/login.tsx
- app/yarn.lock
- server/graph/generated/generated.go
- server/graph/model/models_gen.go
- server/graph/schema.graphqls
- server/graph/schema.resolvers.go
- server/resolvers/forgot_password.go
- server/resolvers/login.go
- server/resolvers/meta.go
- server/resolvers/reset_password.go
- server/test/forgot_password_mobile_test.go
- server/test/forgot_password_test.go
- server/test/integration_test.go
- server/test/reset_password_test.go
Add ability to perform forgot password with SMS based login
Resolves #433
> feat: add forgot password for mobile login

- server/resolvers/test_endpoint.go
- server/utils/webhook.go
> chore: remove refs to deprecated io/ioutil

- internal/integration_tests/add_email_template_test.go
- internal/integration_tests/add_webhook_test.go
- internal/integration_tests/admin_logout_test.go
- internal/integration_tests/delete_email_template_test.go
- internal/integration_tests/delete_user_test.go
- internal/integration_tests/delete_webhook_test.go
- internal/integration_tests/enable_access_test.go
- internal/integration_tests/invite_members_test.go
- internal/integration_tests/revoke_access_test.go
- internal/integration_tests/test_endpoint_test.go
- internal/integration_tests/update_email_template_test.go
- internal/integration_tests/update_webhook_test.go
added test cases for admin api
N/A
N/A
> added admin integration tests
