server/db/roles.go, server/db/session.go, server/db/user.go, server/db/verificationRequests.go
Use golang uuid instead of sql to support all db types.
Also fixes few data types for mysql db
resolves #77
Tested using following docker configs
```
version: '3.3'
services:
db:
image: amd64/mysql:8.0.27
restart: always
environment:
MYSQL_DATABASE: 'db'
MYSQL_USER: 'user'
MYSQL_PASSWORD: 'password'
MYSQL_ROOT_PASSWORD: 'password'
ports:
- '3306:3306'
expose:
- '3306'
volumes:
- my-db:/var/lib/mysql
volumes:
my-db:
```
=> fix: use char(36) with golang uuid instead of sql uuid type

server/constants/constants.go, server/email/email.go, server/env/env.go
Improves SMTP env variable names + support `SENDER_EMAIL`. This will help integrate vendors like send grid.
_Rename:_
- `SENDER_EMAIL` -> `SMTP_USERNAME`
- `SENDER_PASSWORD` -> `SMTP_PASSWORD`
- `SENDER_EMAIL` -> Used as `From` in email
Resolves #94
=> Improve smtp variable names

dashboard/src/graphql/mutation/index.ts, dashboard/src/graphql/queries/index.ts, dashboard/src/pages/Users.tsx, server/db/models/user.go, server/graph/generated/generated.go, server/graph/model/models_gen.go, server/graph/schema.graphqls, server/graph/schema.resolvers.go, server/handlers/oauth_callback.go, server/resolvers/enable_access.go, server/resolvers/login.go, server/resolvers/magic_link_login.go, server/resolvers/revoke_access.go
Update user access from the dashboard.
Admin-only feature.
Describe the solution you'd like
[x] Add field in user schema revoked_timestamp
[x] Add mutation called _revoke_access(param: {user_id: string})
- It should set revoked_timestamp time in user schema
[x] Add Option in dashboard to revoke
[x] Add mutation called _enable_access(param: {user_id: string})
[x] Add Option in the dashboard to activate account
[x] It should take confirmation before revoking
[x] It should take confirmation before activating
[x] It should not allow login/signup for revoked access users for all 3 recipes (basic, social, magiclink)
[ ] Add docs for new API
- https://github.com/authorizerdev/authorizer/issues/135
- https://github.com/authorizerdev/authorizer/issues/143
=> feat: update user access

dashboard/src/constants.ts, dashboard/src/graphql/queries/index.ts, dashboard/src/pages/Environment.tsx, server/constants/env.go, server/env/env.go, server/graph/generated/generated.go, server/graph/model/models_gen.go, server/graph/schema.graphqls, server/handlers/authorize.go, server/handlers/oauth_callback.go, server/handlers/token.go, server/handlers/verify_email.go, server/resolvers/env.go, server/resolvers/login.go, server/resolvers/session.go, server/resolvers/signup.go, server/resolvers/verify_email.go, server/token/auth_token.go, server/utils/parser.go
ACCESS_TOKEN_EXPIRY_TIME env variable can be added in `1h15m15s` format.   
This setting is used for **access_token's** and **id_token's** lifetime.  
Default value = `15m` (in case of absent value or incorrect value).  
May be updated from dashboard interface in `Access token` section.  
[Issue](https://github.com/authorizerdev/authorizer/issues/109)
Update docs PR - [url](https://github.com/authorizerdev/docs/pull/4)
=> enhancement: add access_token_expiry_time env variable

server/resolvers/update_user.go, server/test/update_user_test.go, server/utils/validator.go
Fixes inverted: ``userRoles`` by ``roles``, under utils/validator -> ``IsValidRoles`` func. 
The function was iterating over all env roles and checking if each one existed under the newly inputted roles, causing it to reject, as it should do the opposite. 
Also, I added a comment on the [server/test/update_user_test.go](https://github.com/authorizerdev/authorizer/commit/4ceb6db4ba4920514f09866fe881ce8021ec1e2e#diff-1bf6c2931a0d52dee22f3081290af75a6762bfc5930d470fff7b968debd556c6), explaining the reason behind test error and that in reality succeeds.
#164
=> Unable to update user role fix

Dockerfile
Creates a user `authorizer` in official docker image. This will allow for rootless containers, which is significantly more secure.
=> fix: rootless container

server/handlers/oauth_callback.go, server/oauth/oauth.go
- Fix the default scope for github login
- Adds following scopes `read:user`, `user:email`
=> fix: scope for github auth

server/constants/env.go, server/cookie/admin_cookie.go, server/cookie/cookie.go, server/env/env.go
Adds 2 envs to disable httpOnly cookies
fixes https://github.com/authorizerdev/authorizer/issues/227
Probably the envs section?
=> feat: Add a option to disable httpOnly cookies

server/cookie/cookie.go, server/parsers/url.go
Use sameSite = lax by default
Since app cookie can come from cross site it becomes important to set this in lax mode.
Example person using custom UI on their app domain and making request to authorizer domain.
For more information check:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite
https://github.com/gin-gonic/gin/blob/master/context.go#L86
=> fix(server): use sameSite as lax by default for app cookie

Dockerfile
Updates golang version in docker image to 1.19.1
Resolves #245
=> chore: update golang to 1.19.1

server/handlers/token.go
When you need to get the clientID and clientSecret from the basic auth, codeVerifier SHOULD be set (so != "").
It fixes the OpenID flow for software that use POST forms (per example, Peertube, thanks @skid9000).
=> fix: codeVerifier shouldn't be empty for basic auth

server/parsers/url.go
- Removes extra slash from host, so that issuer verification works correctly
=> fix: remove extra slash from host

server/handlers/oauth_callback.go
The main change in this PR is the modification of the method to access the user's email returned from the Facebook response body during login.This fix resolves an issue with the previous method that caused an auth_callback error, and enables the Facebook login functionality to work as expected, allowing users to successfully log in and register their data.
Issue created in #354 is fixed under this PR.
#354
It doesn't affect any endpoint.
=> Modify the Facebook login authentication callback to enable user email access through the response body.

server/handlers/authorize.go
The original code incorrectly read configured default `respone_mode` value into a variable holding `response_type` value. This causes OAuth2 requests without `response_mode` passed via URL query parameter to fail, because `response_type` value will then be filled with illegal value.
There's no issue at this point. I was testing integration with [Memos](https://usememos.com) and found this coding typo. Their SSO implementation does not pass `response_mode`, thus resulting in error.
There's no API change.
=> Fix wrong response_type parsed when missing response_mode

server/graph/generated/generated.go, server/graph/model/models_gen.go, server/graph/schema.graphqls, server/graph/schema.resolvers.go, server/resolvers/validate_session.go, server/test/resolvers_test.go, server/test/validate_session_test.go
Adds resolver to validate session
Fixes #367
Add docs for `validate_session`
Add helper in authorizer-js
Add helper in authorizer-go
=> feat: add resolver to validate browser session

README.md
Adds a "deploy to Koyeb" button to the "Getting Started" section of the readme file.  This is a companion for the changes proposed in [this PR on the docs repo to add Koyeb documentation](https://github.com/authorizerdev/docs/pull/38) to add an additional deployment target for users. 
None, just a small addition :slightly_smiling_face: 
No API reference docs impacted :+1:
=> Add button to deploy to Koyeb

server/utils/webhook.go
From the Go specification:
> "3. If the map is nil, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary. Example: https://go.dev/play/p/xzuA7WNrkF4
=> refactor(server/utils): remove redundant nil check

app/src/pages/signup.tsx, server/constants/oauth2.go, server/handlers/authorize.go
Enable signup redirection via screen_hint param in /authorize API
=> Feat: add screen_hint param in /authorize api for explicit signup redirection

server/handlers/verify_email.go, server/resolvers/login.go, server/resolvers/signup.go, server/resolvers/verify_otp.go, server/test/mobile_signup_test.go, server/test/verify_email_test.go
Earlier `phone_number_verified_at` was set during the signup when user was not signing up using mobile phone
=> fix: phone_number_verified_at set during signup

server/resolvers/update_user.go
Fix bug where i'm unable to update just app-data. 
When updating with just app-data i get "please enter atleast one param to update". Even though AppData is present in the request.
=> fix unable to update app_data for user

README.md
Adding RepoCloud.io as a one-click deployment option for Authorizer instances. 
Provides deployment diversity and a user-friendly installation option.
=> Added one-click deployment option to readme table

server/handlers/oauth_callback.go
=> Apple outh fix
